version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: dev-file
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8080:8080"
    command: start-dev
    networks:
      - app-network

  app:
    build: ./app
    container_name: express_app
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build: .
    container_name: nginx_openresty
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - keycloak
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=nginx-client
      - KEYCLOAK_CLIENT_SECRET=your-client-secret-here
      - APP_URL=http://app:3000

networks:
  app-network:
    driver: bridge