version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:23.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: dev-file
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8080:8080"
    networks:
      - app-network

  app:
    build: ./app
    container_name: express_app
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build: .
    container_name: nginx_openresty
    # Environment substitution command
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && /usr/local/openresty/nginx/sbin/nginx -g 'daemon off;'"
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
    environment:
      KEYCLOAK_INTERNAL_ENDPOINT: http://keycloak:8080
      KEYCLOAK_EXTERNAL_ENDPOINT: http://192.168.101.13:8080
      KEYCLOAK_LOGOUT_REDIRECT_URI: http://192.168.101.13/
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT: nginx-client
      KEYCLOAK_SECRET: 1Giz1gJyaZEAiSAsH3slrEXz1ayp7aEO
    depends_on:
      - keycloak
      - app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
