version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: >-
      start-dev
      --import-realm
      --hostname-strict=false
      --hostname-url=http://192.168.101.13:8081
      --hostname-admin-url=http://192.168.101.13:8081
      --http-enabled=true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/example-realm.json:/opt/keycloak/data/import/example-realm.json:ro

  api:
    build:
      context: ./api
    environment:
      NODE_ENV: production
      PORT: "3000"
    expose:
      - "3000"
    depends_on:
      - keycloak

  openresty:
    build:
      context: ./openresty
    environment:
      OIDC_DISCOVERY: http://keycloak:8080/realms/example/.well-known/openid-configuration
      OIDC_CLIENT_ID: openresty
      OIDC_CLIENT_SECRET: openresty-secret
      OIDC_REDIRECT_SCHEME: http
      SESSION_SECRET: 723p4hR234t36VsCD8g565325IC0022G
    ports:
      - "8082:8080"
    depends_on:
      - api
      - keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway"


