version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    command: start-dev --hostname keycloak --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json:ro
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/myrealm/.well-known/openid-configuration"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - app-net

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://keycloak:8080/realms/myrealm
      - OAUTH2_PROXY_CLIENT_ID=oauth2-proxy-client
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_UPSTREAMS=http://express-api:3000
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost/oauth2/callback
    ports:
      - "4180:4180"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - app-net

  openresty:
    image: openresty/openresty:alpine
    container_name: openresty
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - oauth2-proxy
      - express-api
    networks:
      - app-net

  express-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: express-api
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge