version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    command: start-dev --hostname 192.168.101.13 --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=192.168.101.13
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT=false
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json:ro
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/myrealm/.well-known/openid-configuration"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - app-net

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://192.168.101.13:8080/realms/myrealm
      - OAUTH2_PROXY_CLIENT_ID=oauth2-proxy-client
      - OAUTH2_PROXY_CLIENT_SECRET=oauth2-proxy-secret
      # - OAUTH2_PROXY_COOKIE_SECRET=OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w=
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_UPSTREAMS=http://express-api:3000
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_REDIRECT_URL=http://192.168.101.13/oauth2/callback
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      # - OAUTH2_PROXY_COOKIE_SECURE=false
      # - OAUTH2_PROXY_COOKIE_HTTP_ONLY=false
      # - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      # - OAUTH2_PROXY_COOKIE_CSRF_EXPIRE=0
      # - OAUTH2_PROXY_COOKIE_CSRF_SAME_SITE=lax
      # - OAUTH2_PROXY_COOKIE_CSRF_SECURE=false
      # - OAUTH2_PROXY_COOKIE_CSRF_HTTP_ONLY=false
      - OAUTH2_PROXY_SKIP_AUTH_REGEX=^/health
      - OAUTH2_PROXY_SKIP_AUTH_STRIP_HEADERS=false
    ports:
      - "4180:4180"
    depends_on:
      - keycloak
    restart: unless-stopped
    networks:
      - app-net

  openresty:
    image: openresty/openresty:alpine
    container_name: openresty
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - oauth2-proxy
      - express-api
    restart: unless-stopped
    networks:
      - app-net

  express-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: express-api
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge