version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: >-
      start-dev
      --import-realm
      --hostname-strict=false
      --hostname-url=http://192.168.101.13:8081
      --hostname-admin-url=http://192.168.101.13:8081
      --http-enabled=true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/example-realm.json:/opt/keycloak/data/import/example-realm.json:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/realms/master/.well-known/openid-configuration >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    restart: unless-stopped

  api:
    build:
      context: ./api
    environment:
      NODE_ENV: production
      PORT: "3000"
    expose:
      - "3000"
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s
    restart: unless-stopped

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://keycloak:8080/realms/example
      OAUTH2_PROXY_CLIENT_ID: openresty
      OAUTH2_PROXY_CLIENT_SECRET: openresty-secret
      OAUTH2_PROXY_COOKIE_SECRET: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_SCOPE: "openid profile email"
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:8082/oauth2/callback
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
    expose:
      - "4180"
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "wget -qO- http://localhost:4180/oauth2/healthz | grep -q 'OK' "]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s
    restart: unless-stopped

  openresty:
    build:
      context: ./openresty
    ports:
      - "8082:8080"
    depends_on:
      api:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      oauth2-proxy:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped


