version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: >-
      start-dev
      --import-realm
      --hostname-strict=false
      --http-enabled=true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/example-realm.json:/opt/keycloak/data/import/example-realm.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/example/.well-known/openid-configuration"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://keycloak:8080/realms/example
      OAUTH2_PROXY_CLIENT_ID: oauth2-proxy
      OAUTH2_PROXY_CLIENT_SECRET: oauth2-proxy-secret
      OAUTH2_PROXY_COOKIE_SECRET: dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXQ=
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:8888/oauth2/callback
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SAMESITE: lax
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
    expose:
      - "4180"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4180/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./api
    environment:
      NODE_ENV: production
      PORT: "3000"
    expose:
      - "3000"

  openresty:
    build:
      context: ./openresty
    depends_on:
      api:
        condition: service_started
      oauth2-proxy:
        condition: service_healthy
    ports:
      - "8888:8888"